// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "agro-data-management-system/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// CropService is an autogenerated mock type for the CropService type
type CropService struct {
	mock.Mock
}

// Create provides a mock function with given fields: crop
func (_m *CropService) Create(crop models.Crop) (models.Crop, error) {
	ret := _m.Called(crop)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Crop
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Crop) (models.Crop, error)); ok {
		return rf(crop)
	}
	if rf, ok := ret.Get(0).(func(models.Crop) models.Crop); ok {
		r0 = rf(crop)
	} else {
		r0 = ret.Get(0).(models.Crop)
	}

	if rf, ok := ret.Get(1).(func(models.Crop) error); ok {
		r1 = rf(crop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *CropService) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *CropService) GetAll() ([]models.Crop, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Crop
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Crop, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Crop); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Crop)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *CropService) GetByID(id int) (models.Crop, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Crop
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Crop, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Crop); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Crop)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: crop
func (_m *CropService) Update(crop models.Crop) error {
	ret := _m.Called(crop)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Crop) error); ok {
		r0 = rf(crop)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCropService creates a new instance of CropService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCropService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CropService {
	mock := &CropService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
