// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "agro-data-management-system/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// FieldService is an autogenerated mock type for the FieldService type
type FieldService struct {
	mock.Mock
}

// Create provides a mock function with given fields: field
func (_m *FieldService) Create(field models.Field) (int, error) {
	ret := _m.Called(field)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Field) (int, error)); ok {
		return rf(field)
	}
	if rf, ok := ret.Get(0).(func(models.Field) int); ok {
		r0 = rf(field)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(models.Field) error); ok {
		r1 = rf(field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *FieldService) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *FieldService) GetAll() ([]models.FieldWithCrop, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.FieldWithCrop
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.FieldWithCrop, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.FieldWithCrop); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FieldWithCrop)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *FieldService) GetByID(id int) (models.FieldWithCrop, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.FieldWithCrop
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.FieldWithCrop, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.FieldWithCrop); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.FieldWithCrop)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: field
func (_m *FieldService) Update(field models.Field) error {
	ret := _m.Called(field)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Field) error); ok {
		r0 = rf(field)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFieldService creates a new instance of FieldService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFieldService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FieldService {
	mock := &FieldService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
