// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "agro-data-management-system/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// ForecastService is an autogenerated mock type for the ForecastService type
type ForecastService struct {
	mock.Mock
}

// GetLatest provides a mock function with given fields: fieldID
func (_m *ForecastService) GetLatest(fieldID int) (models.Forecast, error) {
	ret := _m.Called(fieldID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 models.Forecast
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Forecast, error)); ok {
		return rf(fieldID)
	}
	if rf, ok := ret.Get(0).(func(int) models.Forecast); ok {
		r0 = rf(fieldID)
	} else {
		r0 = ret.Get(0).(models.Forecast)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(fieldID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Predict provides a mock function with given fields: fieldID, pestID
func (_m *ForecastService) Predict(fieldID int, pestID int) (models.Forecast, error) {
	ret := _m.Called(fieldID, pestID)

	if len(ret) == 0 {
		panic("no return value specified for Predict")
	}

	var r0 models.Forecast
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (models.Forecast, error)); ok {
		return rf(fieldID, pestID)
	}
	if rf, ok := ret.Get(0).(func(int, int) models.Forecast); ok {
		r0 = rf(fieldID, pestID)
	} else {
		r0 = ret.Get(0).(models.Forecast)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(fieldID, pestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewForecastService creates a new instance of ForecastService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForecastService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForecastService {
	mock := &ForecastService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
