// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "agro-data-management-system/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MetricService is an autogenerated mock type for the MetricService type
type MetricService struct {
	mock.Mock
}

// GetHistory provides a mock function with given fields: sensorID, from, to
func (_m *MetricService) GetHistory(sensorID int, from time.Time, to time.Time) ([]models.Metric, error) {
	ret := _m.Called(sensorID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []models.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(int, time.Time, time.Time) ([]models.Metric, error)); ok {
		return rf(sensorID, from, to)
	}
	if rf, ok := ret.Get(0).(func(int, time.Time, time.Time) []models.Metric); ok {
		r0 = rf(sensorID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(int, time.Time, time.Time) error); ok {
		r1 = rf(sensorID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatest provides a mock function with given fields: sensorID
func (_m *MetricService) GetLatest(sensorID int) (models.Metric, error) {
	ret := _m.Called(sensorID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 models.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Metric, error)); ok {
		return rf(sensorID)
	}
	if rf, ok := ret.Get(0).(func(int) models.Metric); ok {
		r0 = rf(sensorID)
	} else {
		r0 = ret.Get(0).(models.Metric)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(sensorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: metric
func (_m *MetricService) Save(metric models.Metric) (models.Metric, error) {
	ret := _m.Called(metric)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 models.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Metric) (models.Metric, error)); ok {
		return rf(metric)
	}
	if rf, ok := ret.Get(0).(func(models.Metric) models.Metric); ok {
		r0 = rf(metric)
	} else {
		r0 = ret.Get(0).(models.Metric)
	}

	if rf, ok := ret.Get(1).(func(models.Metric) error); ok {
		r1 = rf(metric)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMetricService creates a new instance of MetricService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricService {
	mock := &MetricService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
