server:
  port: "8080"
  timeout: 30s
database:
  host: "localhost"
  port: 5432
  ssl_mode: "disable"
test_database:
  host: "localhost"
forecasting:
  python_service_url: "http://localhost:8000"
weather_api:
  base_url: "https://api.meteotrek.ua"
  login: ""
  password: ""
