// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "agro-data-management-system/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// ForecastRepository is an autogenerated mock type for the ForecastRepository type
type ForecastRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: f
func (_m *ForecastRepository) Create(f models.Forecast) (models.Forecast, error) {
	ret := _m.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Forecast
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Forecast) (models.Forecast, error)); ok {
		return rf(f)
	}
	if rf, ok := ret.Get(0).(func(models.Forecast) models.Forecast); ok {
		r0 = rf(f)
	} else {
		r0 = ret.Get(0).(models.Forecast)
	}

	if rf, ok := ret.Get(1).(func(models.Forecast) error); ok {
		r1 = rf(f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ForecastRepository) GetByID(id int) (models.Forecast, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Forecast
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Forecast, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Forecast); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Forecast)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistoryByField provides a mock function with given fields: fieldID
func (_m *ForecastRepository) GetHistoryByField(fieldID int) ([]models.Forecast, error) {
	ret := _m.Called(fieldID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryByField")
	}

	var r0 []models.Forecast
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.Forecast, error)); ok {
		return rf(fieldID)
	}
	if rf, ok := ret.Get(0).(func(int) []models.Forecast); ok {
		r0 = rf(fieldID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Forecast)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(fieldID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestByField provides a mock function with given fields: fieldID
func (_m *ForecastRepository) GetLatestByField(fieldID int) (models.Forecast, error) {
	ret := _m.Called(fieldID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestByField")
	}

	var r0 models.Forecast
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Forecast, error)); ok {
		return rf(fieldID)
	}
	if rf, ok := ret.Get(0).(func(int) models.Forecast); ok {
		r0 = rf(fieldID)
	} else {
		r0 = ret.Get(0).(models.Forecast)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(fieldID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewForecastRepository creates a new instance of ForecastRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForecastRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForecastRepository {
	mock := &ForecastRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
