// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "agro-data-management-system/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MetricRepository is an autogenerated mock type for the MetricRepository type
type MetricRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: metric
func (_m *MetricRepository) Create(metric models.Metric) (models.Metric, error) {
	ret := _m.Called(metric)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Metric) (models.Metric, error)); ok {
		return rf(metric)
	}
	if rf, ok := ret.Get(0).(func(models.Metric) models.Metric); ok {
		r0 = rf(metric)
	} else {
		r0 = ret.Get(0).(models.Metric)
	}

	if rf, ok := ret.Get(1).(func(models.Metric) error); ok {
		r1 = rf(metric)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistoryBySensor provides a mock function with given fields: sensorID, from, to
func (_m *MetricRepository) GetHistoryBySensor(sensorID int, from time.Time, to time.Time) ([]models.Metric, error) {
	ret := _m.Called(sensorID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryBySensor")
	}

	var r0 []models.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(int, time.Time, time.Time) ([]models.Metric, error)); ok {
		return rf(sensorID, from, to)
	}
	if rf, ok := ret.Get(0).(func(int, time.Time, time.Time) []models.Metric); ok {
		r0 = rf(sensorID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(int, time.Time, time.Time) error); ok {
		r1 = rf(sensorID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAggregatedMetricsByField provides a mock function with given fields: fieldID, from, to
func (_m *MetricRepository) GetAggregatedMetricsByField(fieldID int, from time.Time, to time.Time) ([]models.MetricAggregate, error) {
	ret := _m.Called(fieldID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregatedMetricsByField")
	}

	var r0 []models.MetricAggregate
	var r1 error
	if rf, ok := ret.Get(0).(func(int, time.Time, time.Time) ([]models.MetricAggregate, error)); ok {
		return rf(fieldID, from, to)
	}
	if rf, ok := ret.Get(0).(func(int, time.Time, time.Time) []models.MetricAggregate); ok {
		r0 = rf(fieldID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MetricAggregate)
		}
	}

	if rf, ok := ret.Get(1).(func(int, time.Time, time.Time) error); ok {
		r1 = rf(fieldID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestBySensor provides a mock function with given fields: sensorID
func (_m *MetricRepository) GetLatestBySensor(sensorID int) (models.Metric, error) {
	ret := _m.Called(sensorID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBySensor")
	}

	var r0 models.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Metric, error)); ok {
		return rf(sensorID)
	}
	if rf, ok := ret.Get(0).(func(int) models.Metric); ok {
		r0 = rf(sensorID)
	} else {
		r0 = ret.Get(0).(models.Metric)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(sensorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMetricRepository creates a new instance of MetricRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricRepository {
	mock := &MetricRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
