// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "agro-data-management-system/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// PestRepository is an autogenerated mock type for the PestRepository type
type PestRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: pest
func (_m *PestRepository) Create(pest models.Pest) (models.Pest, error) {
	ret := _m.Called(pest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Pest
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Pest) (models.Pest, error)); ok {
		return rf(pest)
	}
	if rf, ok := ret.Get(0).(func(models.Pest) models.Pest); ok {
		r0 = rf(pest)
	} else {
		r0 = ret.Get(0).(models.Pest)
	}

	if rf, ok := ret.Get(1).(func(models.Pest) error); ok {
		r1 = rf(pest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *PestRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *PestRepository) GetAll() ([]models.Pest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Pest
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Pest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Pest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Pest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *PestRepository) GetByID(id int) (models.Pest, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Pest
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Pest, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Pest); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Pest)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: pest
func (_m *PestRepository) Update(pest models.Pest) error {
	ret := _m.Called(pest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Pest) error); ok {
		r0 = rf(pest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPestRepository creates a new instance of PestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PestRepository {
	mock := &PestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
