// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "agro-data-management-system/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// SensorRepository is an autogenerated mock type for the SensorRepository type
type SensorRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: sensor
func (_m *SensorRepository) Create(sensor models.Sensor) (models.Sensor, error) {
	ret := _m.Called(sensor)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Sensor
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Sensor) (models.Sensor, error)); ok {
		return rf(sensor)
	}
	if rf, ok := ret.Get(0).(func(models.Sensor) models.Sensor); ok {
		r0 = rf(sensor)
	} else {
		r0 = ret.Get(0).(models.Sensor)
	}

	if rf, ok := ret.Get(1).(func(models.Sensor) error); ok {
		r1 = rf(sensor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *SensorRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByFieldID provides a mock function with given fields: fieldID
func (_m *SensorRepository) GetByFieldID(fieldID int) ([]models.Sensor, error) {
	ret := _m.Called(fieldID)

	if len(ret) == 0 {
		panic("no return value specified for GetByFieldID")
	}

	var r0 []models.Sensor
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.Sensor, error)); ok {
		return rf(fieldID)
	}
	if rf, ok := ret.Get(0).(func(int) []models.Sensor); ok {
		r0 = rf(fieldID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Sensor)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(fieldID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *SensorRepository) GetByID(id int) (models.Sensor, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Sensor
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Sensor, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Sensor); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Sensor)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: id, status
func (_m *SensorRepository) UpdateStatus(id int, status models.SensorStatus) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, models.SensorStatus) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSensorRepository creates a new instance of SensorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSensorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SensorRepository {
	mock := &SensorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
