graph LR
    subgraph " Веб-система "
        UC1((Перегляд даних з датчиків))
        UC2((Отримання прогнозу появи шкідників))
        UC3((Керування полями та культурами))
        UC4((Автоматичне сповіщення про ризики))
    end

    Admin[fa:fa-user Агроном]
    System[fa:fa-robot Система прогнозування]

    Admin --- UC1
    Admin --- UC2
    Admin --- UC3
    Admin --- UC4

    UC2 --- System
    UC4 --- System

    style UC1 fill:#a5f,stroke:#333,stroke-width:2px
    style UC2 fill:#a5f,stroke:#333,stroke-width:2px
    style UC3 fill:#a5f,stroke:#333,stroke-width:2px
    style UC4 fill:#a5f,stroke:#333,stroke-width:2px